apiVersion: v1
kind: PersistentVolume
metadata:
  name: codigo-node
spec:
  storageClassName: node
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path : /home/luis/dev/api
