apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node
  namespace : dev-api
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: node
